---
- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes
  become: true

- name: Verify Java installation
  command: java -version
  register: java_version_output
  changed_when: false

- name: Show Java version
  debug:
    var: java_version_output.stderr_lines
